### PR TITLE
Moving swagger specification into the web server. Removed Flasgger an…

### PR DESCRIPTION
**Pull request by zroadhouse-rmn**
…d directly added Swagger-UI v2.2.5 to be able to visualize the API docs

### CODE REVIEW

**Comment by ophiradi** [comment]
The swagger api will be available via /apidocs static endpoint.  Do we want it to be retrievable by api call for those not using the UI?

**Comment by ophiradi** [comment]
Also, "The command "python src/python/dart/tool/export_swagger_definitions.py src/python/dart/web/api/swagger.yaml --dry-run" failed and exited with 1 during ." in the travis build

**Comment by zroadhouse-rmn** [comment]
The swagger API is available at /api/1/swagger.json. That's how Swagger UI is able to get to the API specification. Neither end point requires authentication.

**Comment by zroadhouse-rmn** [comment]
I'll modify the build to "pip install -e ." to make the Dart modules available for the scripts.

**Comment by zroadhouse-rmn** [comment]
Hopefully travis will run through with no issues after my second fix commit (source path was wrong in the first one).

**Comment by zroadhouse-rmn** [comment]
Looks like my latest changes are working now in TravisCI. From the log:

$ pip install -e src/python
Obtaining file:///home/travis/build/RetailMeNotSandbox/dart/src/python
Installing collected packages: dart
  Running setup.py develop for dart
Successfully installed dart

$ python src/python/dart/tool/export_swagger_definitions.py src/python/dart/web/api/swagger.yaml --dry-run
No changes.

**Comment by zroadhouse-rmn** [comment]
One thing that I can think of that is missing is updating the API URL in the returned swagger specification to point to the server's API. I can fix that.

**Comment by zroadhouse-rmn** [comment]
Perhaps the apidocs / swagger UI end-point should be authenticated so that its possible to invoke the APIs from the UI without running into errors prior to authenticating?

**Comment by zroadhouse-rmn** [comment]
Updated the endpoint to include the API URL. Didn't change anything about the authentication. We can see how it goes with the apidocs and swagger being accessible without login.

**Pull request merged**
